---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove any previous version of the key from the known hosts file
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: 192.168.177.42
        state: absent
      delegate_to: localhost
    - name: Build the known hosts file
      ansible.builtin.shell: ssh-keyscan 192.168.177.42 >> ~/.ssh/known_hosts
      register: keyscan_key

- hosts: server
  become: true
  become_user: root
  tasks:
    - name: Upgrade apt repo and cache on Debian box
      when: ansible_os_family == "Debian"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all packages on Debian servers
      when: ansible_os_family == "Debian"
      apt: upgrade=yes force_apt_get=yes
    - name: Check if a reboot is required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- hosts: server
  become: true
  become_user: root
  tasks:
    - name: Retrieve Ansible key and add repo
      when: ansible_os_family == "Debian"
      block:
        - name: Retrieve Ansible apt-key
          ansible.builtin.get_url:
            url: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
# It appears from https://github.com/ansible/ansible/issues/78063#issuecomment-1210837515 that apt
# will accept these files without dearmoring them, as long as the extension is .asc
            dest: /etc/apt/keyrings/ansible-archive-keyring.asc
            mode: '0644'
            force: true
        - name: Add Ansible repository to apt
# For Debian 12, use the Ubuntu codename of jammy to get the latest distribution
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/ansible-archive-keyring.asc] http://ppa.launchpad.net/ansible/ansible/ubuntu jammy main"
        - name: Update apt cache with Ansible repository
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        - name: Install Ansible
          apt:
            name:
              - ansible
              - ansible-lint
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

- hosts: server
  become: true
  become_user: root
  tasks:
    - name: Retrieve OpenTofu key and add repo
      when: ansible_os_family == "Debian"
      block:
        - name: Retrieve OpenTofu apt-key
          ansible.builtin.get_url:
            url: https://get.opentofu.org/opentofu.gpg
# It appears from https://github.com/ansible/ansible/issues/78063#issuecomment-1210837515 that apt
# will accept these files without dearmoring them, as long as the extension is .asc
            dest: /etc/apt/keyrings/opentofu.asc
            mode: '0644'
            force: true
        - name: Retrieve OpenTofu packages apt-key
          ansible.builtin.get_url:
            url: https://packages.opentofu.org/opentofu/tofu/gpgkey
# It appears from https://github.com/ansible/ansible/issues/78063#issuecomment-1210837515 that apt
# will accept these files without dearmoring them, as long as the extension is .asc
            dest: /etc/apt/keyrings/opentofu-repo.asc
            mode: '0644'
            force: true
        - name: Add OpenTofu repository to apt
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/opentofu.asc,/etc/apt/keyrings/opentofu-repo.asc] https://packages.opentofu.org/opentofu/tofu/any/ any main"
        - name: Add OpenTofu source repository to apt
          ansible.builtin.apt_repository:
            repo: "deb-src [signed-by=/etc/apt/keyrings/opentofu.asc,/etc/apt/keyrings/opentofu-repo.asc] https://packages.opentofu.org/opentofu/tofu/any/ any main"
        - name: Update apt cache with OpenTofu repository
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        - name: Install OpenTofu
          apt:
            name:
              - tofu
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
